bobMinimumVersion: "1.2"
layers:
  - name: basement
    scm: git
    url: https://github.com/BobBuildTool/basement.git
    commit: eb620056e3fb58b67a93373d33be414749f4f3f8
  - name: basement-gnu-linux
    scm: git
    url: https://github.com/BobBuildTool/basement-gnu-linux.git
    commit: 365fa977952a9ccc91b137dad8e2fec49565fa37
