bobMinimumVersion: "1.1"
layers:
  - name: basement
    scm: git
    url: https://github.com/BobBuildTool/basement.git
    commit: 0938c1795632763a1d4e9f3bdf7084243ae57d13
  - name: basement-gnu-linux
    scm: git
    url: https://github.com/BobBuildTool/basement-gnu-linux.git
    commit: 75cc9292eb584736c69bc746ccb40c14b0ce2f15
