bobMinimumVersion: "1.1"
layers:
  - name: basement
    scm: git
    url: https://github.com/BobBuildTool/basement.git
    commit: d42250e42f8fa2e0de9281c8bf42e0ada2d108b3
  - name: basement-gnu-linux
    scm: git
    url: https://github.com/BobBuildTool/basement-gnu-linux.git
    commit: 3c1019f9cfc9e66c2ac2d8ad0af91958ccf46180
